### ISSUE TITLE
No information on acknowledging ARC

### ISSUE THREAD

**Issue by drjbarker** [arcdocs/arcdocs.github.io#13]
The previous website had a section on how to acknowledge ARC in publications. This seems to have dissappeared. Is it still required? I've never been asked for a list of publications which acknowledge ARC either.

**Comment by NGRhodes** [comment]
Old page can be accessed at https://arc-old.leeds.ac.uk/using-the-systems/arc-acknowledgement/
Does need migrating to the new docs website.

**Comment by Sparrow0hawk** [comment]
Hi @drjbarker this is definitely something we've accidentally missed and will rectify. We definitely do still want researchers to acknowledge ARC in their publications and should be in touch soon requesting information about publications acknowledging ARC (this is a relatively new scheme by the RC Team).
