### ISSUE TITLE
Issue on page usage/scratch.html

### ISSUE THREAD

**Issue by jhliang01** [arcdocs/arcdocs.github.io#156]
Hi, I found that the third row of the table under the ARC4 local disk specifications section (https://arcdocs.leeds.ac.uk/usage/scratch.html#) is a bit unclear. It shows that the Local Disk Capacity is 128B for GPU notes, but does it mean 128GB? Thanks.

**Comment by Sparrow0hawk** [comment]
Hi @jhliang01 👋 

Thanks so much for raising this issue with us! @jhodrien has suggested a fix to this which we'll look at approving and updating into our documentation.

Thanks for helping improve arcdocs! ❤️
