### ISSUE TITLE
Issue on page /software/start.html

### ISSUE THREAD

**Issue by dhvalden** [arcdocs/arcdocs.github.io#16]
Im missing several pages of documentation about the libraries installed on the arc

**Comment by Sparrow0hawk** [comment]
You can find all the old docs at https://arc-old.Leeds.ac.uk

Let us know which docs you're looking for and I can include them in a new pull request.

**Comment by Sparrow0hawk** [comment]
@dhvalden can you let us know which pages in particular are missing so we can fix this? Thanks!

**Comment by dhvalden** [comment]
It mainly in the documentation section here https://arcdocs.leeds.ac.uk/software/start.html. While there you can find most of the software install, the list of shared libraries and python libraries that was in the other site is missing, which is very useful for people using python or compiling their tools there. I worked around having a user library but i guess is not ideal. also, the interpreters version are missing.

I think all of this can be worked around if you post a manual of how to use module to navigate the available libraries, but i dont know if this works for the python libs.

Thanks a lot!

**Comment by jhodrien** [comment]
I think what we're really missing is a page on Python in the software section, that lists the recommended way to use Python on ARC, which is most likely to not use python-libs and use anaconda.

**Comment by jhodrien** [comment]
An anaconda page now exists, showing a recommended way of using it for Python.
