### ISSUE TITLE
The version of Ansys we use as an example of loading an old version (17.1) doesn't exist on ARC 4. Not sure it really matters though. I'll approve anyway.

### ISSUE THREAD

**Issue by jhodrien** [arcdocs/arcdocs.github.io#175]
The version of Ansys we use as an example of loading an old version (17.1) doesn't exist on ARC 4. Not sure it really matters though. I'll approve anyway.

_Originally posted by @ollie-clark in https://github.com/arcdocs/arcdocs.github.io/pull/170#pullrequestreview-1628435843_

**Comment by Tiany1Pan** [comment]
@jhodrien The relevant section (additional license setup) has been moved to the legacy Ansys section, do you think if we can close this issue?

**Comment by jhodrien** [comment]
Resolved by #193
