### ISSUE TITLE
Connecting to ARC via WSL

### ISSUE THREAD

**Issue by paddy-r** [arcdocs/arcdocs.github.io#184]
I've managed to connect to ARC4 via SSH on a Windows machine through WSL (only tested with Ubuntu BTW; I say "managed", it was actually dead easy). Is it worth me adding something to the docs [here](https://arcdocs.leeds.ac.uk/getting_started/logon/logon-off-campus.html) on that option? Might be some users who prefer that to using MobaXTerm. The steps are exactly as in the instructions for Mac/Linux.

**Comment by agdturner** [comment]
Thanks Hugh, it is good to know you got this working. I don’t think we need to add anything to the documentation. WSL with a flavour of Linux should be regarded as that Linux and connections via WSL should simply follow the instructions for connecting via Linux once the instance is running. Thanks 😊
