### ISSUE TITLE
Running on login nodes

### ISSUE THREAD

**Issue by drjbarker** [arcdocs/arcdocs.github.io#35]
Maybe it can be featured more prominently in the docs or even in the login message not to do big runs on the login nodes. I almost never see one of the login nodes not being fully loaded by some user(s) running big jobs. It seems to seriously slow down login times too (today I double checked my internet connection hadn't gone down in the time it took to ssh in). Below is a screenshot from today, clearly John has reniced some people but then new users have joined the party.

![image](https://user-images.githubusercontent.com/53377004/103884873-1b3b6480-50d7-11eb-96f1-beeeb87e7b20.png)

**Comment by Sparrow0hawk** [comment]
We're going to take this as a general thing to do as you say and look at how we can be more explicit about not using login nodes across the docs.

I'd say we do try and police it and do very much emphasise it in our training courses, sadly though not everyone attends those (although we're looking at trying to address this in our next training revamp).

I'm going to close this but feel free to add more, and if you come across serial offenders we don't catch feel free to reach out via https://bit.ly/arc-help
